name: duet
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  camera: ^0.9.4+16
  video_player: ^2.0.0
  image_picker: ^0.8.4+11
  flutter_ffmpeg: ^0.4.2
  gallery_saver: ^2.3.2
  path_provider: ^2.0.9
  flutter_video_info: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
